"""
Action Handler Generator: Generates Python action handler scripts.

This module generates Python scripts that are invoked by Klish ACTION elements
to interact with the REST API.
"""

import os
from typing import Dict, Any


class ActionHandlerGenerator:
    """Generates Python action handler scripts."""
    
    def __init__(self):
        pass
    
    def generate(self, module_name: str, parsed_yang: Dict[str, Any], output_path: str):
        """
        Generate Python action handler script.
        
        Args:
            module_name: Name of the YANG module
            parsed_yang: Parsed YANG model dictionary
            output_path: Path to write the generated Python script
        """
        handler_name = f'sonic-cli-{module_name}.py'
        
        script_content = self._generate_handler_script(module_name, parsed_yang)
        
        with open(output_path, 'w') as f:
            f.write(script_content)
        
        print(f"Generated action handler: {output_path}")
    
    def _generate_handler_script(self, module_name: str, parsed_yang: Dict[str, Any]) -> str:
        """Generate the Python action handler script content."""
        
        script = f'''#!/usr/bin/env python3
"""
Auto-generated action handler for {module_name}
Generated by: sonic-klish-gen

This script handles CLI actions for the {module_name} module.
"""

import sys
import json
import requests
from collections import OrderedDict


REST_API_BASE = "http://localhost:8080/restconf/data"


def make_rest_call(method, path, data=None):
    """
    Make a REST API call.
    
    Args:
        method: HTTP method (GET, POST, PATCH, DELETE)
        path: REST API path
        data: Optional data payload
    
    Returns:
        Response data or None
    """
    url = f"{{REST_API_BASE}}/{{path}}"
    headers = {{"Content-Type": "application/json"}}
    
    try:
        if method == "GET":
            response = requests.get(url, headers=headers)
        elif method == "POST":
            response = requests.post(url, headers=headers, json=data)
        elif method == "PATCH":
            response = requests.patch(url, headers=headers, json=data)
        elif method == "DELETE":
            response = requests.delete(url, headers=headers)
        else:
            print(f"Unsupported HTTP method: {{method}}", file=sys.stderr)
            return None
        
        if response.status_code in [200, 201, 204]:
            if response.content:
                return response.json()
            return None
        else:
            print(f"REST API error: {{response.status_code}} - {{response.text}}", file=sys.stderr)
            return None
    
    except Exception as e:
        print(f"Error making REST call: {{e}}", file=sys.stderr)
        return None


'''
        
        for table in parsed_yang.get('tables', []):
            table_name = table.get('name')
            
            if 'static-objects' in table:
                for obj in table['static-objects']:
                    obj_name = obj.get('name')
                    for attr in obj.get('attrs', []):
                        attr_name = attr.get('name')
                        script += self._generate_patch_function(
                            module_name, table_name, obj_name, attr_name
                        )
            
            if 'dynamic-objects' in table:
                for obj in table['dynamic-objects']:
                    obj_name = obj.get('name')
                    keys = obj.get('keys', [])
                    attrs = obj.get('attrs', [])
                    
                    script += self._generate_add_function(
                        module_name, table_name, obj_name, keys, attrs
                    )
                    script += self._generate_delete_function(
                        module_name, table_name, obj_name, keys
                    )
        
        script += '''

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: {} <function_name> [args...]".format(sys.argv[0]), file=sys.stderr)
        sys.exit(1)
    
    function_name = sys.argv[1]
    args = sys.argv[2:]
    
    if function_name in globals():
        try:
            result = globals()[function_name](*args)
            if result is not None:
                print(json.dumps(result, indent=2))
        except Exception as e:
            print(f"Error executing {function_name}: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(f"Unknown function: {function_name}", file=sys.stderr)
        sys.exit(1)
'''
        
        return script
    
    def _generate_patch_function(self, module_name: str, table_name: str, 
                                 obj_name: str, attr_name: str) -> str:
        """Generate a PATCH function for setting an attribute."""
        func_name = f'patch_{table_name.lower()}_{obj_name.lower()}_{attr_name.lower()}'
        
        return f'''

def {func_name}(value):
    """
    Set {table_name}/{obj_name}/{attr_name} to the specified value.
    
    Args:
        value: Value to set
    
    Returns:
        Response data or None
    """
    path = "{module_name}:{table_name}/{obj_name}"
    data = {{
        "{module_name}:{obj_name}": {{
            "{attr_name}": value
        }}
    }}
    
    print(f"Setting {table_name}/{obj_name}/{attr_name} = {{value}}")
    return make_rest_call("PATCH", path, data)
'''
    
    def _generate_add_function(self, module_name: str, table_name: str, 
                               obj_name: str, keys: list, attrs: list) -> str:
        """Generate an ADD function for adding a list entry."""
        func_name = f'add_{table_name.lower()}_{obj_name.lower()}'
        
        params = [key.get('name').lower() for key in keys]
        params.extend([attr.get('name').lower() for attr in attrs])
        params_str = ', '.join(params)
        
        data_items = []
        for key in keys:
            key_name = key.get('name')
            data_items.append(f'            "{key_name}": {key_name.lower()}')
        for attr in attrs:
            attr_name = attr.get('name')
            data_items.append(f'            "{attr_name}": {attr_name.lower()}')
        data_dict = ',\n'.join(data_items)
        
        return f'''

def {func_name}({params_str}):
    """
    Add a new entry to {table_name}/{obj_name}.
    
    Args:
        {', '.join([p + ': ' + p for p in params])}
    
    Returns:
        Response data or None
    """
    path = "{module_name}:{table_name}/{obj_name}"
    data = {{
        "{module_name}:{obj_name}": [{{
{data_dict}
        }}]
    }}
    
    print(f"Adding entry to {table_name}/{obj_name}")
    return make_rest_call("POST", path, data)
'''
    
    def _generate_delete_function(self, module_name: str, table_name: str, 
                                  obj_name: str, keys: list) -> str:
        """Generate a DELETE function for removing a list entry."""
        func_name = f'delete_{table_name.lower()}_{obj_name.lower()}'
        
        params = [key.get('name').lower() for key in keys]
        params_str = ', '.join(params)
        
        key_path = ','.join([f'{{{key.get("name").lower()}}}' for key in keys])
        
        return f'''

def {func_name}({params_str}):
    """
    Delete an entry from {table_name}/{obj_name}.
    
    Args:
        {', '.join([p + ': ' + p for p in params])}
    
    Returns:
        Response data or None
    """
    path = f"{module_name}:{table_name}/{obj_name}={key_path}"
    
    print(f"Deleting entry from {table_name}/{obj_name}")
    return make_rest_call("DELETE", path)
'''
