"""
Template Generator: Generates Jinja2 show templates.

This module generates Jinja2 templates used by show commands to format output.
"""

import os
from typing import Dict, Any


class TemplateGenerator:
    """Generates Jinja2 show templates."""
    
    def __init__(self):
        pass
    
    def generate(self, module_name: str, parsed_yang: Dict[str, Any], output_dir: str):
        """
        Generate Jinja2 show templates.
        
        Args:
            module_name: Name of the YANG module
            parsed_yang: Parsed YANG model dictionary
            output_dir: Directory to write the generated templates
        """
        os.makedirs(output_dir, exist_ok=True)
        
        for table in parsed_yang.get('tables', []):
            table_name = table.get('name')
            
            if 'static-objects' in table:
                template_path = os.path.join(
                    output_dir,
                    f'show_{module_name.replace("-", "_")}_{table_name.lower()}.j2'
                )
                self._generate_static_template(
                    module_name, table_name, table['static-objects'], template_path
                )
            
            if 'dynamic-objects' in table:
                for obj in table['dynamic-objects']:
                    obj_name = obj.get('name')
                    template_path = os.path.join(
                        output_dir,
                        f'show_{module_name.replace("-", "_")}_{obj_name.lower()}.j2'
                    )
                    self._generate_dynamic_template(
                        module_name, table_name, obj, template_path
                    )
        
        print(f"Generated Jinja templates in: {output_dir}")
    
    def _generate_static_template(self, module_name: str, table_name: str, 
                                  static_objects: list, output_path: str):
        """Generate a Jinja2 template for static objects."""
        
        template_content = f'''{{# Auto-generated Jinja template for show {module_name} {table_name.lower()} #}}
{{# Generated by: sonic-klish-gen #}}

{table_name} Configuration
{'=' * (len(table_name) + 14)}

{{% if '{module_name}:{table_name}' in data %}}
{{% set config = data['{module_name}:{table_name}'] %}}

'''
        
        for obj in static_objects:
            obj_name = obj.get('name')
            template_content += f'''{obj_name}:
'''
            for attr in obj.get('attrs', []):
                attr_name = attr.get('name')
                template_content += f'''  {attr_name}: {{{{ config.{obj_name}.{attr_name} | default('N/A') }}}}
'''
            template_content += '\n'
        
        template_content += '''{{% else %}}
No configuration found.
{{% endif %}}
'''
        
        with open(output_path, 'w') as f:
            f.write(template_content)
    
    def _generate_dynamic_template(self, module_name: str, table_name: str, 
                                   obj: Dict[str, Any], output_path: str):
        """Generate a Jinja2 template for a dynamic object (list)."""
        
        obj_name = obj.get('name')
        keys = obj.get('keys', [])
        attrs = obj.get('attrs', [])
        
        headers = [key.get('name') for key in keys]
        headers.extend([attr.get('name') for attr in attrs])
        
        col_widths = [max(20, len(h)) for h in headers]
        
        template_content = f'''{{# Auto-generated Jinja template for show {module_name} {obj_name.lower()} #}}
{{# Generated by: sonic-klish-gen #}}

{obj_name} Entries
{'=' * (len(obj_name) + 8)}

{{% if '{module_name}:{table_name}' in data %}}
{{% set entries = data['{module_name}:{table_name}']['{obj_name}'] %}}

'''
        
        header_format = '%-' + 's %-'.join(str(w) for w in col_widths) + 's'
        template_content += f'''{{{{'{header_format}'|format({', '.join([f"'{h}'" for h in headers])})}}}}
{{{{'-' * {sum(col_widths) + len(col_widths) - 1}}}}}
'''
        
        template_content += '{{% for entry in entries %}\n'
        row_items = []
        for key in keys:
            key_name = key.get('name')
            row_items.append(f'entry.{key_name}')
        for attr in attrs:
            attr_name = attr.get('name')
            row_items.append(f'entry.{attr_name} | default("N/A")')
        
        template_content += f'''{{{{'{header_format}'|format({', '.join(row_items)})}}}}
'''
        template_content += '{{% endfor %}\n\n'
        template_content += '''Total: {{{{ entries | length }}}} entry(ies)

{{% else %}}
No entries found.
{{% endif %}}
'''
        
        with open(output_path, 'w') as f:
            f.write(template_content)
